name: Deploy to ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  frontend-domain: emojify.net

  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}

jobs:
  build-and-upload-frontend:
    name: build and upload frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create env file
        run: |
          touch .env
          echo REACT_APP_GOOGLE_ANALYTICS_TRACKING_ID=${{ env.GA_TRACKING_ID }} >> .env

      - name: Push build to S3 (destructive!)
        env:
          STACK_NAME: ${{ env.stack-name }}
          CLOUDFRONT_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        run: |
          bun install
          bun run build
          aws s3 sync ./dist s3://${{ env.frontend-domain }} --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/index.html" "/favicon.ico" "/robots.txt" "/icon-192.png" "/icon-512.png" "/manifest.json"
